---
- name: Configuración de aplicacion - voting app
  hosts: all
  become: yes

  vars_files:
    - ../inventories/dev/group_vars/vars.yml

  roles:
    - apt
    - database
    - redis
    - app
    - vote
    - result
    - worker
    