---
# tasks file for vote

- name: Instalar dependencias del sistema para voting app
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
    update_cache: yes

- name: Instalar dependencias Python para voting app
  pip:
    requirements: "{{ app_dir }}/roxs-voting-app/vote/requirements.txt"
    virtualenv: "{{ venv_path }}"
    virtualenv_command: "python3 -m venv"

- name: Crear archivo de servicio systemd para voting
  template:
    src: voting.service.j2
    dest: /etc/systemd/system/voting.service
    owner: root
    group: root
    mode: 0644

- name: Recargar systemd para aplicar cambios en voting
  command: systemctl daemon-reload

- name: Habilitar y arrancar el servicio voting
  systemd:
    name: voting
    enabled: yes
    state: started