---
# tasks file for worker

- name: Instalar dependencias de Worker (Node.js)
  npm:
    path: "{{ app_dir }}/roxs-voting-app/worker"

- name: Crear archivo de servicio systemd para worker
  template:
    src: worker.service.j2
    dest: /etc/systemd/system/worker.service
    owner: root
    group: root
    mode: 0644

- name: Recargar systemd para aplicar cambios en worker
  command: systemctl daemon-reload

- name: Habilitar y arrancar el servicio worker
  systemd:
    name: worker
    enabled: yes
    state: started