Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"

  # Red privada para acceso interno
  config.vm.network "private_network", ip: "192.168.56.101"

  # Redirección de puertos
  config.vm.network "forwarded_port", guest: 5000, host: 8080  # Flask app
  config.vm.network "forwarded_port", guest: 3000, host: 3000  # Result app
  config.vm.network "forwarded_port", guest: 6379, host: 6379  # Redis
  config.vm.network "forwarded_port", guest: 5432, host: 5432  # PostgreSQL

  # Provisionamiento con Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/main.yml"
    ansible.inventory_path = "inventories/dev/host"
    ansible.verbose = "vvv"  # Opcional: más salida de depuración
  end
end
